env:
  global:
    - TZ=Asia/Shanghai

language: node_js # 设置语言
node_js: stable # 设置相应版本

branches:
  only: # 只监测hexo分支
    - gh-pages
    - /.*/

git:
  depth: false
  submodules: false

cache:
  apt: true
  directories:
    - node_modules # 缓存不经常更改的内容

before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - git config user.name "MrLeo"
  - git config user.email "leo@xuebin.me"
  - npm install hexo-cli -g # 安装hexo环境

install: npm install

before_script:

script:
  # - hexo clean
  - hexo deploy -g
