# https://hadronw.com/2018/05-27/travis-autodeploy-github-with-coding/

env:
  global:
    - TZ=Asia/Shanghai
    - GH_REF: github.com/MrLeo/blog.git #设置GH_REF，注意更改成自己的仓库地址

language: node_js # 设置语言
node_js: v10.16.3 # stable # 设置相应版本

branches:
  only: # 只监测hexo分支
    # - gh-pages
    # - /.*/
    - master

git:
  depth: false
  submodules: false

cache:
  apt: true
  directories:
    - node_modules # 缓存不经常更改的内容

before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - git config user.name "MrLeo"
  - git config user.email "leo@xuebin.me"
  - npm install hexo-cli -g # 安装hexo环境
  - chmod +x ./publish-to-gh-pages.sh # 为shell文件添加可执行权限

install: npm install

before_script:

script:
  - hexo clean
  - hexo g

after_script:
  - ./publish-to-gh-pages.sh
